#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EQRSDroid.Resource", IsApplication=true)]

namespace EQRSDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::EQRSDroid.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::EQRSDroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fire = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int meds = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ndis = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int police = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int ClockText = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int DialogNavText = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int GoBackButton = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int IncrementButton = 2131034123;
			
			// aapt resource value: 0x7f050013
			public const int NavigationParameterText = 2131034131;
			
			// aapt resource value: 0x7f050010
			public const int SendMessageButton = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int ShowDialogButton = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int TapText = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int WelcomeText = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int buttonCrime = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int buttonFire = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int buttonMedical = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int buttonNatDisaster = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int buttonReport = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int checkBox1 = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int gridLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int listViewEmergencies = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int progressBar1 = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int textView1 = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EmergencyDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EmergencyList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Second = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
